sudo: false

language: ruby
rvm: 2.3.1

before_install: chmod +x ./bin/setup
install: ./bin/setup

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --enforce-https --check-favicon --only-4xx --allow-hash-href
